### ISSUE TITLE
Mutational profile data?

### ISSUE THREAD

**Issue by spark157** [allydunham/aa_subtypes#1]
Hello and great paper. In looking through the repo I was tyring to find a file that would contain the mutational profile (ie.  the vector of a position’s ER scores) that I would be able to use to construct a mutational landscape for a sequence of interest. If I'm understanding correctly there should be a vector for each amino acid. 

Thanks if you can point me in the direction to assemble this info.

Scott

**Comment by spark157** [comment]
Hi again,

I think I can answer my own question. The data appears to all be consolidated in:
combined_mutational_scans.tsv

I understand now that there is a mutational profile for each position and for each protein. I somehow had in my head (incorrectly) that they were combined along the way to a more general representation. 

Scott

**Comment by allydunham** [comment]
Hi,

Sorry for the delay, I wasn't set to recieve notifications on the repo for some reason.

You're correct, the combined_mutational_scans.tsv file contains the ER profile for each protein position in the dataset, along with other data collected about that position (SIFT score, etc.)

Ally
