### ISSUE TITLE
UMAP question

### ISSUE THREAD

**Issue by spark157** [allydunham/aa_subtypes#2]
Hello,

I'm gathering that when UMAP was applied to the data was it applied to all 6291 mutational profiles at the same time and these are 20 dimensional vectors. Is that the case?

I can see the stored values as umap1 and umap2 in combined_mutational_scans.tsv - were these calculated in another scripy (not appearing in the repo)?

Thanks.
Scott

**Comment by allydunham** [comment]
Yes, UMAP is calculated accross all positions.

As far as I know all scripts I used are in the repo, in this case `bin/data_processing/combine_standardised_data.R` generates `combined_mutational_scans.tsv` including calculating UMAP. It requires the raw study data however, which can't be included in the repo and has to be downloaded separately to run the initial processing up to `combined_mutational_scans.tsv` (see the readme for pipeline details).

Best,
Ally
