### ISSUE TITLE
Post-translational modification sites

### ISSUE THREAD

**Issue by spark157** [allydunham/aa_subtypes#3]
In the paper under Discussion you have the following: "A form of subtype we would expect to find with more data is post-translational modification sites such as phosphosites."

Just to clarify my understanding: this would be the case since with more data you would be able to reliably cluster the mutational profiles (using the same methodology as in the paper) and discover/uncover this subtype ?

Thanks for the clarification.

Scott

**Comment by allydunham** [comment]
We would expect positions that have post-translational modifications to have different mutational profiles (at least in broad terms), meaning they would form their own cluster with enough phosphosite examples in the data, yes.

Best,
Ally
