### ISSUE TITLE
Clustering question

### ISSUE THREAD

**Issue by spark157** [allydunham/aa_subtypes#4]
You mentioned trying several clustering algorithms, methods etc. to cluster amino acid positions. I was curious did you try HDBSCAN and/or UMAP?

Thanks.

Scott

**Comment by allydunham** [comment]
The different clustering configurations I tried are in yaml files in meta/subtypes/. These config files are then passsed to bin/analysis/2_subtypes/make_subtypes.R which handles clustering. As you can see I did try various versions of HDBSCAN (none were particularly sucessful). I didn't try using the UMAP coordinates to cluster, only PCA.

Ally
